#+TITLE:      自我管理

* 目录                                                    :TOC_4_gh:noexport:
- [[#松鼠症---焦虑症---懒癌][松鼠症 -> 焦虑症 -> 懒癌]]
- [[#相关链接][相关链接]]

* 松鼠症 -> 焦虑症 -> 懒癌
  #+begin_quote
  *松鼠症*
  智能移动终端设备真是个好工具，可以让我们利用碎片化时间学习。上下班途中、工作累的时候、排队买东西、上厕所五谷轮回、晚上卧床的时候，掏出移动终端就是一阵又一阵的狂刷朋友圈转发的高能文章、读各种APP里面推送的前沿资讯。一篇接着一篇，浏览完了一篇就感觉好有道理，技能值+1，感觉学习学上了瘾，好有成就感；看了两篇发现要看的文章太多了，然后就是朋友圈转发Mark下，微博里的鸡汤收藏下，知乎里醍醐灌顶的回答收藏再转发朋友圈，心想厉害的文章太多了，等有空了再细细品读。

  等过几天发现，在十几个APP里收藏的各领域的文章增加了几十篇，忽然感慨原来老夫/老娘碎片化时间学习效率这么高啊，这样下来不出两年时间就能“上知天文、下知地理、中晓人和、运筹帷幄之中、决胜千里之外”，我骄傲！然而发现那几十篇文章从来都没有读过啊，等有空了再读吧。再过几天，突然要用到之前收藏过的文章了，“你见，或者不见我；我就在那里”，找不到那篇文章可咋整？有问题找度娘……

  若觉得上面的场景就是你每天津津乐道干的事，那只能很不幸的告诉您，您有病了，还是绝症——“松鼠症”。

  松鼠症定义：学名强迫性囤积症，是种心理疾病。患者喜欢囤积物品，坚信某天会用上，但最后实际囤积物几乎用不到。这种病症很容易让人的生活陷入混乱。

  不过不要慌张，你的“松鼠症”还是初期，最起码你平时囤积的物品是用来学习的文章，初衷是好的，只要对症服药，很快就能康复，而且技能值蹭蹭往上涨。而那些整天在刷娱乐、刷八卦、刷短视频、刷直播、疯狂追剧的患者，就属于中晚期了，也有救，药不能停。

  *焦虑症*
  “松鼠症”患者，在刷刷刷、攒攒攒的自我感觉贼棒的日子中，随着不断点开新的文章，有一种莫名的上了瘾的自嗨型廉价快感，让人沉浸其中欲罢不能。不知不觉已经积攒了数百篇文章，但，都没读过；读过的文章也都是浅阅读，没有经过加工、思考、交流，这些知识在短期记忆里暂存的当天就被排挤出去了，根本就没有内化为自己的知识。突然某个时刻，你发现收藏的文章越多，越会给你产生永远也看不完的压力感，你就再也不想着去消化收藏的文章了。怎么办？搁置争议继续刷刷刷、攒攒攒。

  周而复始，让本来想通过这些文章不断进步，不断跟上时代节奏的你，发现自己还是原地踏步，跟那些写文章大牛的差距越拉越大，而且会涌现一茬又一茬的新大V、公知不断赶上那些牛人，你被狠狠的抛在了后面。你开始怀疑两年时间就能“上知天文、下知地理”的鸿鹄之志，沮丧感油然而生，你看透了这一切，陷入不断的焦虑状态不能自拔。

  焦虑症定义：又称为焦虑性神经症，是神经症这一大类疾病中最常见的一种，以焦虑情绪体验为主要特征。

  *懒癌*
  “焦虑症”患者不断的越来越焦虑，终于有一天爆发了，干嘛天天刷刷刷、攒攒攒啊，干嘛碎片化学习啊，都是唬人的，都是那些自媒体为了商业目的想骗我的钞票的，我是一个平凡的人，上班够累的了，我要刷娱乐、刷八卦、刷短视频、刷直播、疯狂追剧。遇到要做的事情，拖延症又犯了，再严重点就懒癌了。

  懒癌定义：懒癌有一定潜伏期，前兆是拖延症。手头的事情多到做不完，每当下决心去做事情时，就会不自主的哼着小曲、唱个歌、吃着火锅、剁个手。“懒”是人的本性，但是如果明知自己很“懒”，却无法改善，慢慢的就会发展成为“懒癌”。

  懒癌犯了一段时间，你又觉得虽然我很平凡，但我决不能接受自己的平庸。好了，开始进入新一轮的循环吧……
  #+end_quote

  解决方法：
  + 知识管理（ VS 松鼠症）：构建知识输入、个人产出的知识体系
  + 目标管理（ VS 焦虑症）：计划制定与管理，行动确定与完成
  + 时间管理（ VS 懒　癌）：行动落地实施，有使命感的高效学习

  来源：[[https://www.jianshu.com/p/4606565d195c][患了三大绝症，该如何构建知识、目标、时间管理体系？ - 简书]]

* 相关链接
  + [[https://wiki.mbalib.com/wiki/%E8%87%AA%E6%88%91%E7%AE%A1%E7%90%86%E8%83%BD%E5%8A%9B][自我管理能力 - MBA 智库百科]]

