#+TITLE:      八段锦

* 目录                                                    :TOC_4_gh:noexport:
- [[#口诀与动作][口诀与动作]]
  - [[#两手托天理三焦][两手托天理三焦]]
  - [[#左右开弓似射雕][左右开弓似射雕]]
  - [[#调理脾胃须单举][调理脾胃须单举]]
  - [[#五劳七伤向后瞧][五劳七伤向后瞧]]
  - [[#摇头摆尾去心火][摇头摆尾去心火]]
  - [[#两手攀足固肾腰][两手攀足固肾腰]]
  - [[#攒拳怒目增气力][攒拳怒目增气力]]
  - [[#背后七颠百病消][背后七颠百病消]]
- [[#呼吸节奏][呼吸节奏]]
- [[#注意事项][注意事项]]
- [[#相关问题][相关问题]]
  - [[#八段锦什么时候练最好][八段锦什么时候练最好]]
  - [[#八段锦练多久才有效][八段锦练多久才有效]]
  - [[#八段锦练习时的注意事项][八段锦练习时的注意事项]]
  - [[#八段锦的版本选择][八段锦的版本选择]]

* 口诀与动作
** 两手托天理三焦
   直立，两足分开，与肩同宽。两臂自然松垂身侧，然后徐徐自左右侧方上举至头顶，两手手指相叉，翻掌，掌心朝上如托天状，同时顺势踮两脚跟，再将两臂放下复原，同时两脚跟轻轻着地。如此反复多遍。

   易犯错误：两掌上托不充分，抬头不够；两掌保持抻拉时，松懈断劲；两掌下落时，肩臂僵硬。

   纠正方法：两掌上托时抬头看手，下颏先向上助力，再内收配合两掌上撑，力达掌根，保持伸拉两秒；两掌下落时要先沉肩、坠肘，而后手臂自然下落，身体中正，松腕舒指。

** 左右开弓似射雕
   直立，左足跨出一大步，身体下蹲作骑马式。两臂在胸前交叉，右臂在外，左臂在内，眼看左手，然后左手握拳，食指翘起向上，拇指伸直与食指成八字撑开。接着左臂向左推出并伸直，头随而左转，眼看左手食指，同时右手握拳，展臂向右平拉作拉弓状。动作复原后左右互换，反复进行数次。

   易犯错误：开弓时端肩，塌腰，重心偏移；成马步时跪腿，收腿时脚擦地、晃动，步法不灵便。
   
   纠正方法：开弓时立项沉肩，上体直立，充分转头，步法转换要清晰，开弓时马步的膝关节不得超过脚尖，两掌侧撑时移为横裆步。在习练过程中，根据自身情况调整马步高度，不可强求，避免动作变形，循序渐进地发展下肢力量。

** 调理脾胃须单举
   直立，两足分开，与肩同宽。右手翻掌上举，五指并紧，掌心向上，指尖向右，同时左手下按，掌心向下，指尖向前。动作复原后，两手交替反复进行，反复多遍。

   易犯错误：两臂在上撑、下按时，掌指方向不正；肘关节僵直，没有弯曲度；两臂对拉力度不够，上体不够舒展。

   纠正方法：上举和下按时两掌放平，指尖摆正；在肘关节稍屈的状态下体会两肩充分拉伸。

** 五劳七伤向后瞧
   直立，两足分开，与肩同宽。两手掌心紧贴腿旁，然后头慢慢左顾右盼向后观望。同时配合呼吸，向后望时吸气，复原时呼气。

   易犯错误：两臂外旋时上体后仰；转头与旋臂不充分。

   纠正方法：两臂外旋时下颏微收，向后转动时上体中正；转头时看斜后下方45°，旋臂时小拇指侧最大限度外旋，保持两秒抻拉。

** 摇头摆尾去心火
   两足分开，相距约三个足底的长度，屈膝半蹲成骑马势。两手张开，虎口向内，扶住大腿前部。头部及上体前俯，然后作圆环形转腰，转动数圈后再反方向转腰。在转腰的同时，适当摆动臀部。

   易犯错误：摇转时头部僵直，尾闾转动不圆活；摇转时挺胸展腹，上体后仰。

   纠正方法：转头时，颈部肌肉尽量放松，不可主动用力，头部转动速度要慢于尾闾转动；向后转动头部时要含胸，抬头向上看，向前转动尾闾时要收腹，向后转动时要先塌腰，再敛臀立身。
   在马步状态下转动尾闾有一定难度，可以将动作分解练习，先体会头部摇转，再体会尾闾转动，最后将转头和转动尾闾结合起来。

** 两手攀足固肾腰
   直立，并足，两膝挺伸、上身前俯，以两手攀握两足趾，头略昂起。然后恢复直立姿势，同时两手握拳，并抵于腰椎两侧，上身缓缓后仰，再恢复直立姿势。重复几遍。

   易犯错误：两手向下摩运时低头，膝关节弯曲；向上起身时，起身在前，举臂在后。

   纠正方法：两手向下摩运时稍抬头，膝关节伸直，可根据自身身体状况自行调整动作幅度；向上起身时以臂带身，两臂贴近双耳。

** 攒拳怒目增气力
   两腿分开屈膝成骑马势，两手握拳放在腰旁，拳心向上。左拳向前方缓缓击出，右臂伸直，拳心向下，两眼睁大，向前虎视。然后收回左拳，如法击出右拳，左右交替进行。

   易犯错误：冲拳时上体前俯，塌腰、耸肩、掀肘；旋腕幅度不够；拳回收时抓握无力。

   纠正方法：冲拳时上体正直，百会上领，下颏微收，肩部松沉，前臂贴肋前送，力达拳面；拳回收时，先五指伸直充分旋腕，再屈指用力抓握。

** 背后七颠百病消
   直立，并足，两掌紧贴腿侧，两膝伸直，足跟并拢提起，离地数寸，同时昂首，作全身提举势。然后足跟轻轻着地复原，反复进行。

   易犯错误：提踵时耸肩，身体重心不稳；下落颠足时速度快，用力过大。

   纠正方法：提踵时五趾抓地，两腿并拢，提肛收腹，肩向下沉，立项竖脊，百会上领；向下颠足时先缓缓下落一半，而后轻震地面。

* 呼吸节奏
  + [[http://www.chinesekungfu.com.cn/html/1203/3626af65-6342-4c66-865f-77021cfb8833.htm][八段锦呼吸方法谈——鞠作常 王承旭 ——中国武术在线 武术流派]]

* 注意事项
  + 如果要配合呼吸，那么应该让呼吸自然一点，不要太用力
  + 吸气对应肌肉绷紧，呼气对应肌肉放松
  + 忌猛忌滞

* 相关问题
** 八段锦什么时候练最好
   如果可以选择早晨进行练习，对于上班族来说可以选择晚上，当然，除了这两个时间段以外，其他时间也可以随便练练。

   不过需要注意：吃饱饭后不能练八段锦，乱玩八段锦也不能立刻吃饭，要在饭前、饭后的半小时后练。

** 八段锦练多久才有效
   大多数人练八段锦 3-6 个月才会看见效果，具体因人而异。所以说不要因为短期的练习没有效果就选择放弃。

** 八段锦练习时的注意事项
   1) 合适的环境，尽量可以呼吸到新鲜空气
   2) 宽松的衣物
   3) 练后不可立即吃饭 - 半个小时后
   4) 练后不可马上洗澡 - 半个小时后
   5) 练后不可吸烟
   6) 练后不可饮酒
   7) 练后不可立即蹲下休息

** 八段锦的版本选择
   八段锦常见的版本有：国家体育总局发布的八段锦版本、少林八段锦、武当八段锦。

   而版本的选择应该选择适合自己的，可以在熟悉了其中一个版本后再去尝试其他的版本，
   综合选择最适合自己的一个版本。

