#+TITLE:      2021-01-自控力

* 目录                                                    :TOC_4_gh:noexport:
- [[#自控力][自控力]]
- [[#footnotes][Footnotes]]

* 自控力
  ☞ [[https://book.douban.com/subject/10786473/][自控力 (豆瓣)]]

  所谓意志力，就是控制自己的注意力、情绪和欲望的能力。而在这个花花绿绿的时代，人们的意志力时常遭受着全方位的挑战。
  
  现实中，网络上，都充斥着很多由专业人士，花费大量时间金钱，利用科学方法精心为你准备的礼物，吸引你的注意力，
  影响你的情绪，掏空你的钱包（或身体⁄(⁄ ⁄•⁄ω⁄•⁄ ⁄)⁄）。

  老爹说过，要用科学打败科学。自控力作为广受好评的一本书，站在个人的视角，通过九个章节，让我们认识到：
  1. 我们的意志力是存在问题的，会因为生理或心理上的缺陷[fn:1]，或者仅仅是状态上的不好就失控，
     甚至进入一个「失控 -> 状态变差 -> 继续失控」的恶性循环
  2. 我们失控的原因是什么
  3. more……

  看完这本书后，我的感受就是，我的自控力可能没有得到什么提升，但是，我 *对失控的认知* 发生了变化，接受失控这一事实，
  不要过多的苛责自己，同时如何去避免下一次的失控。

  这也是在这本书的序言上提到的：提高自控力的最有效途径在于，弄清楚自己如何失控，为何失控。

  -----

  *生理层面的认知*

  我们的意志力由大脑中的 *前额皮质* 掌管，醉酒、缺觉、分心等都会影响到它，使我们无法控制自己的冲动。
  #+begin_quote
  重点：醉酒，缺觉，分心等都会影响到它。特别是熬夜，很多人都有一个早睡早起的梦，但是因为熬夜，使得前额皮质受到影响，
  忍受不住手机的诱惑，早睡失败，继续熬夜……

  然后是分心，《自控力》第一章中提到可以通过冥想[fn:2]来训练自己，提高注意力，当然，其他提高注意力的训练也是可以的。
  #+end_quote

  我们的意志力受「心率变异度」的影响，心率变异度越高，我们越能更好的集中注意力，避免即时行乐的想法。
  而任何给你的身心带来压力的东西都会影响自控力的生理基础，降低心率变异度。
  #+begin_quote
  简单来说，就是压力会让你失控，这里的压力包括但不限于焦虑、愤怒、抑郁和孤独、慢性疾病。也就是说，缓解压力也是极为总要的，
  但是，缓解压力的方式不包括抽烟、酗酒、暴饮暴食、长时间打游戏和看（刷）视频……

  合适的缓解压力的方式为：锻炼、保持良好的睡眠、健康饮食、听音乐。
  #+end_quote

  DIO：JOJO，人的意志力是有极限的，我从短暂的人生中学到一件事……越是控制自己，就越会发现人类的意志力是有极限的……除非超越人类
  #+begin_quote
  就像 DIO 说的那样，人的意志力是有极限的，用得太多会疲惫，这是正常的。
  #+end_quote
  
  欲望的基础，在可能获得潜在的奖励的时候，我们大脑中的多巴胺含量会上升，让我们感到兴奋。这里的特殊在于，引起多巴胺分泌的不是获得奖励这个结果，
  而是获得奖励的可能性。
  #+begin_quote
  奖励可能是多种多样的，抽卡时可能的 5 星角色，刷视频时可能的好看的视频，购物。多巴胺本来的作用是正面的，我们的欲望也来源于此，
  多巴胺分泌的缺失可能导致抑郁，让人失去「渴望」感，很多东西提不起劲……

  但，多巴胺带来的兴奋具有成瘾性，在持续的多巴胺刺激结束后，失落感会让人继续寻求更多的多巴胺，去刷视频，去抽卡，去消费……

  问题就在于，引起多巴胺的分泌并不需要让人真的获得奖励，因此，抽卡可以让你抽不到 5 星，而是告诉你，多少多少可能会抽到，
  最后掏空你的钱包。

  这没有很好的办法去避免，只能由我们自己来识别什么是有益的真实奖励，什么是让我们分散精力、上瘾的虚假奖励。区分出来，改变认知，
  这样，当奖励不再是奖励，诱惑自然也就失效了。

  比如将抽卡认知为骗钱（但是角色很可爱，所以值得）。
  #+end_quote

  面临压力时（愤怒、悲伤、焦虑、自我怀疑等），会使你的大脑进入寻找奖励的状态，此时，你的大脑会将 *奖励* 和 *可能获得奖励* 关联起来，
  让你去做会让你的多巴胺变多的事情。
  #+begin_quote
  正如前面所说，抽烟、酗酒、刷视屏等都只是让你通过多巴胺引起的兴奋遮掩了压力，并没有真正释放压力，多巴胺消失后，失落感会让压力变得更大。

  正确的释放压力的方式是锻炼、阅读、音乐等。

  不要在压力面前相信你的冲动，你的大脑还没有那么智能。
  #+end_quote

  前额皮质最擅长的不是自控。它会为错误的决定寻找接口，向我们承诺，明天会更好。
  #+begin_quote
  明日复明日，明日何其多也。我们的大脑更倾向于即时的奖励，同时，会把未来的自己识别为陌生人，不断地给未来的自己增加负担。

  比如作业，一枝笔，一个晚上，一个奇迹。

  避免的办法：
  + 想象自己已经获得了长远奖励的样子，人们相比于即时的奖励，更不愿意放弃已经得到的奖励，这能在一定程度上起到缓解的作用
  + 面临眼前的诱惑时等待 10 分钟，冷静下来后再做选择（但是现在很多即时诱惑都是限时的 QAQ）
  + 想象未来的自己，降低未来的自己的陌生感，让向未来的自己增加负担变得沉重
  #+end_quote

  大脑中的镜像神经元通过对其他人进行模仿来理解其他人的行为，这种模仿会让我们的意志力受到其他人的影响，这主要可以分为：
  + 来自亲近的人的影响，我们的一些行为会下意识地和亲近的人靠近，如果和你亲近的人有坏习惯，那么你很有可能就会被感染
  + 来自大多数人的影响，大多数人都是那样，会让我们觉得那样不再是一个问题，从而放纵自己
  #+begin_quote
  好的坏的习惯都会在你的社交圈子里面传染，近朱者赤，近墨者黑，选择筛选自己的社交圈子，或者时常回忆一下自己的目标，
  反思一下自己最近的行为，有哪些受到了别人的影响。
  
  这种模范和传染最大的问题就在于是下意识就完成了的，在我们还没有意识到的情况下就已经完成了，反之，如果能认识到，那么，
  就会有了「抗体」，被传染的概率大幅降低。

  而多数人问题，在我们发现大多数人都和自己一样有一样的问题的时候，我们就会感到放松，「还好还好，我跟别人一样」。我们需要认识到，
  多数人都那样不代表那样就是正确的。
  #+end_quote

  *心理层面的认知*
  
  当我们做了自认为正确的事后，我们很有可能会觉得自己应该受到赞扬，转而作为奖励自己的一种行为，我们会去做一些不正确的事情。
  #+begin_quote
  我已经学习了……，所以今天休息一下好了之类的。这样的想法可以扩展到任意取得正面成果后的场景：学习、戒烟、戒酒、取得进步，
  然后，为了犒赏自己，之前的成功全部木大。

  甚至不需要真的取得正面的成果，只是幻想一下取得正面成果也行，本质上，我们只是需要一个放纵自己的接口而已。

  这种情况下，在要放纵自己的时候，想一下自己以前的时候为什么能拒绝诱惑，为什么要拒绝诱惑，你为什么要做这件事。我不是为了玩去学习的，
  而是为了获得知识，取得进步去学习的。如果我现在去玩了，那么这和我最初的目标是背道而驰的。这不是奖励。

  取消许可（奖励），牢记理由。
  #+end_quote

  当你想改变某种行为的时候，试着减少行为的变化性，而不是减少那种行为。
  #+begin_quote
  在试着一次性把某种坏习惯根除时，突如其来的改变会让人感到不适，带来额外的压力，容易坚持不下来。步子跨太大容易***，
  所以，试着一点一点地来，时间还很长，一点一点来，持之以恒总能成功。
  #+end_quote

  只要使你放纵的东西和使你觉得品德高尚的东西同时出现，就会产生光环效应，让你觉得，放纵不再是不好的东西。
  #+begin_quote
  常见套路，双十一之类的诱惑活动，容易让人觉得购买优惠后的商品 = 省钱，因此，会让人冲动去购买平时想买有不敢买的东西。

  但实际上：省钱不是买到便宜的东西，而是在支出限额内买到便宜的东西。
  #+end_quote

  那又如何，当你的自控计划失败后，你会对自己感到失望，这会带来压力，会让你想做一些改善心情的事情。那么，最廉价、最快捷的改善心情的方法是什么？
  往往是导致你情绪低落的事。
  #+begin_quote
  和前面的压力导致的冲动一样，只不过，这次的压力来源变成了自己的自控失败，这让你感到失望，让你觉得，既然我的 xx 计划已经失败，
  那么我继续 xx 也没什么了，反正都失败了。

  在这里，我们需要的是原谅自己，而不是苛责自己。想想，如果是你的朋友遇到挫折了，你会是去苛责太还是安慰他？人无完人，
  每个人都有失败的时候，很多人的自控计划经常失败，你只是其中微不足道的一份子，这次失败了，下次来过即可。
  #+end_quote

  下定决心会让我们立刻有了放松感个控制感，我们不再觉得自己是个犯错的人，只觉得自己能变成一个完全不同的人。
  #+begin_quote
  常见现象，放假前决定说回去看书、学习、这样那样，在下定决心，作出这个计划的时候，我们感觉充满了希望，想象之后完成计划的自己，
  得到了满足。

  搭嘎，这里的一个问题是：我们什么都还没做，就已经感觉良好了，得到了满足。

  而现实，往往充满不确定性，事情的发展很难完全按照计划来，然后，当自己发现自己的计划失败了，挫折感带来的压力会让人像前面那样，
  寻求释放压力。

  然后继续做计划，下决心，再失败……

  这被叫做「虚假希望综合征」，它总是偷偷出现，并伪装成自控的样子。

  避免这一问题的办法是乐观地作出计划，悲观地预测计划可能的失败。计划不总是能成功，接收可能的失败，重振旗鼓。
  #+end_quote

  讽刺性反弹，试图压抑自己的想法、情绪和欲望，往往只会产生想法的效果，让你更容易去想、去感受、去做你原本想逃避的事。
  #+begin_quote
  有时，我们会遇到拼命不去想某件事，但关于那件事的想法还是不断冒出来的情况。这似乎是人的一种本能，我们无法真的控制自己的思想。

  对于这种情况，我们需要的是：
  1) 承认自己脑海中的欲望，以及渴望某种事物的感觉
  2) 不要马上试着转移注意力会与之争论。接受这种想法或感觉，提醒自己讽刺性反弹理论
  3) 退一步考虑，意识到这种想法和感觉并不受你控制，但你可以选择是否将这些想法付诸实践，记住，抑制欲望的反面不是自我放纵
  4) 记住你的目标，提醒自己预先作出的承诺
  #+end_quote

* Footnotes

[fn:1] 这里的缺陷只是一个形容词，没有这样的缺陷的话，人类可能会得到像机器人一样的自律能力，但是，真的那样的话，
也太过无趣了一点 ●ｖ●

[fn:2] 这里的冥想不是让你什么都不想，而是专注注意力到到呼吸上，避免 *分心* 

