#+TITLE:      2021-02-斯坦福高效睡眠法

* 目录                                                    :TOC_4_gh:noexport:
- [[#认知][认知]]
- [[#方法][方法]]

* 认知
  与睡眠有关的烦恼和精神压力，是无法仅通过「对量的确保」来解决的。
  #+begin_quote
  前段时间，每天我基本能保证 9 个小时左右的睡眠，但是白天的状态依然不是很好，出于这一困扰，我打开了这本书，
  然后，在序言就看到了这句话。

  于是，我决定读下去。
  #+end_quote

  睡眠可以分为 REM 睡眠和非 REM 睡眠两类，可以简单地理解为非深度睡眠和深度睡眠，入睡后，两类睡眠交替出现，
  首先出现的就是非 REM 睡眠（深度睡眠），这是整个睡面过程中深度睡眠持续最长的一次。
  #+begin_quote
  睡眠的质量便由这最初的深度睡眠决定，大约在 90 分钟左右。所以，要想睡眠质量好，入睡初期的状态是极为重要的。
  #+end_quote

  缺少睡眠时，白天就有可能会瞬间进入 1 到 10 秒的睡眠状态，由于时间很短，所以当事者本人和周围的人都很难注意到。
  #+begin_quote
  假如是开车的人或从事危险工作的人进入了瞬间睡眠状态，就问你怕不怕。
  #+end_quote

  理想睡眠时长因人而异，不要因为别人睡的短就觉得自己也可以，同时，过短和过长的睡眠都不利于健康。
  #+begin_quote
  有时，早上起床的时候会进入一种怎么也睡不够的状态，就像睡昏了一样，明明醒了，但似乎又可以继续睡下去，
  不知道是不是睡觉时间太长的原因。
  #+end_quote

  午休是一个好习惯，但也不要睡的太久，一般 20-30 分钟是一个比较合适的时长，在进入深度睡眠状态前起来就好。
  #+begin_quote
  一般中午睡一小会就能够清除昏沉沉的感觉了，反而睡久了会感觉没睡够，想继续睡。
  #+end_quote

  仅仅偿还 40 分钟的睡眠负债，就需要在 3 周的时间里每天都睡 14 小时，这是不现实的。
  #+begin_quote
  尽可能的保证你的睡眠质量，周内熬夜周末补觉虽然有效果，但也极为有限。
  #+end_quote

  入睡时体内温度下降，体表温度上升，因此，让自己快速入睡的一个办法就是降低体内和体表的温差。
  #+begin_quote
  裸睡的一大好处，体表散热快，睡着还很舒服。
  #+end_quote

  规律作息时间，相对固定的入睡和起床时间能够带给你更好的睡眠质量。同时，入睡前的两个小时反而是最难入睡的，
  因此，也不要过早的躺在床上。
  #+begin_quote
  给你的大脑一个认知，床是睡觉的地方，睡不着就起来。
  #+end_quote

  清醒时的状态也决定了能否睡得香。
  #+begin_quote
  睡觉的时候睡觉，吃饭的时候吃饭，不要晚上想着玩，白天却想着睡觉。
  #+end_quote

  个人想法：
  1. 保证晚上有一个好的睡眠质量，白天在清醒的状态下玩，应该是比白天睡觉，晚上玩更加舒服的。
     虽然现实中可能因为各种原因导致白天没有什么时间玩，但也尽量不要透支晚上的时间。

     结合《自控力》书中的说法，白天的压力容易让你在晚上寻求放松，这时，睡觉才是最好的放松方法，
     而手机、游戏虽然能为你带来多巴胺，让你感到兴奋，但不会为你带来真正的放松。

     虽然你会感觉手机是一个不错的选择，但是别在压力下相信你的冲动。

  2. 时间还长，早睡早起，你在晚上玩的时间可能少了，但是早起可以让你白天多一点自由时间，而且，
     就算今天没时间了，明天，周六，周末还有。不要局限于现在。

* 方法
  我是在这个[[https://www.zhihu.com/question/311297911/answer/594670379][知乎回答]]的影响下才去看这本书的，这个回答中对书中的方法总结的已经很好了，我也懒得抄一遍了。

  其他一些这个回答中没提到的点：
  1. 保持规律的作息很重要，但周六周日的早晨比平时多睡 1-2 个小时并不算什么问题，但不要晚睡
  2. 午睡的姿势：侧躺 -> 仰躺椅子上 -> 趴在桌子上
  3. 不要未来工作而牺牲自己的睡眠，特别是在你想要完成创作性工作时
  4. Better than nothing，白天犯困后小睡一下还是比不睡要好的，但不要睡太久，20 分钟左右就好

