#+TITLE:      步入社会

* 目录                                                    :TOC_4_gh:noexport:
- [[#社保][社保]]
- [[#毕业生关于三方户口档案五险一金问题][毕业生关于三方、户口、档案、五险一金问题]]
- [[#购房资格][购房资格]]
- [[#报道证][报道证]]

* 社保
  社保和社保卡需要分开来了解：
  + 社保和你的养老保险、医疗保险、失业保险、工伤保险和生育保险相关，社保的参保和社保卡无关，
    但是参保地是很重要的一个属性
  + 社保卡是你使用社保的一个途径，不同地方的社保卡可能不同，在换工作的时候，可能需要办理新的社保卡

  注：社保卡和社保相关，但不影响社保的参保，只影响社保的使用
  
* 毕业生关于三方、户口、档案、五险一金问题
  + 实习指的是尚未毕业的学生到用人单位进行的社会实践活动，所以企业是不能和已经毕业的学生签署实习协议的

  + 对毕业生来说，三方协议是一份从拿到 offer 到入职签署劳动合同前的保障协议。在国内大学读书的应届毕业生在首次就业时，需要毕业生本人、学校和用人单位三方签订。三方协议一旦签署，就意味着第一份工作基本确定。

    在签三方协议之前，记得将你的福利待遇要求在备注栏里写清楚，避免日后用人单位不认账或者降低你的福利待遇，或者说一套，做一套。

  + 三方协议由各地教育局制定，签署顺序为：学生 > 用人单位 > 学校（由学校发给学生签署，学生填完交给用人单位签署，用人单位签署完由学生交给学校签署）

    某些国家机关、事业单位或国企会要求毕业生入职后将档案派遣到这些用人单位，因为档案的派遣会影响职称的评定，如果档案没有派遣到用人单位，则无法评定职称。

    如果毕业生确定未来会前往民营企业或外资企业工作，三方协议的签署就没那么重要。就算不签署三方协议，也可以在签署劳动合同后，从学校或者生源地将档案派遣到用人单位或所在地的人才中心。

  + 在签署三方协议时，有些用人单位会加入违约金的相关条款。之所以加入这样的条款主要是因为用人单位在招聘时，投入了相关的资金、人力成本，如果毕业生违约，用人单位需对相关职位重新进行招聘，增加了成本。

    从法律的角度上来说，三方协议是由学校作为见证，毕业生与用人单位签订的一份意向性协议，它具有法律效力。三方协议中的“违约金”并没有专门的法律规定，它主要是适用于《民法通则》或《合同法》的相关规定，只要是当事人的真实意愿，即为有效。若违约就应按协议约定承担违约金赔偿责任。

  + 《劳动合同法》第十七条规定了劳动合同的法定形式是书面形式，其必备条款有 9 项，签订劳动合同时要特别留意：

    劳动合同除前款规定的必备条款外，用人单位与劳动者可以约定试用期、培训、保守秘密、补充保险和福利待遇等其他事项。

  + Offer 就是录用通知（或者说工作邀请），由用人单位向毕业生（求职者）发出，是获得工作的第一步，但在这三者中效力较小

    三方协议：由学校、毕业生、用人单位三方签订，是比较正式的就业意向协议，由学校来协助保障毕业生的求职利益。

  + 集体户口是指暂时还不具备单独立户条件，或者暂时还没有办理单独立户手续的居民，其户籍关系挂靠在某一个集体户头上的居民户口。依据各地政策，如果用人单位达到设立集体户口的条件，可申请设立单位集体户口。毕业生可依据当地政策选择是否迁入单位集体户。用人单位没有集体户的情况下，毕业生可依据当地政策选择迁入当地人才中心或者迁回生源地。

  + 上文提到，集体户口是户籍关系挂靠在某一个集体户头上的居民户口，这个集体户头可以是某个没有亲属关系的个人，或者单位。通常情况下集体户口与个人户口无异；但如果挂靠的是单位，需要注意的是：单位集体户口是在你还是单位的员工 的基础上有效，一旦解除劳动合同则需要户口迁移。个人户口也就是家庭户口，就是我们通常意义上的户口了，具备单独立户条件，其户籍关系挂靠在自己或者配偶 / 直系亲属的房产上的居民户口。

  + 档案是个人经历、政治面貌、品德作风等的历史记录文档。现阶段，在档案的主要作用有：凭证、依据和参考等等，而普通公民主要利用的是档案的凭证作用。由于档案具有其真实性、原始性，具有其它任何材料不可替代的依据和凭证作用，所以它有很强的法律效力。对于个人来说，无论是工作调动、出国政审、职称评审、工资调整、劳动保险，还是入党团以及离退休手续的办理、各项证明的出具等等手续都将以档案的审核为重要依据。

  + 大学生在入学时，档案会调入学校，由学校代为保管。毕业时如果找到工作，需调出。如果没有找到合适的工作（或考研），可向学校申请延缓就业，由学校代为保管，最长 2 年时间。在 2 年内找到工作后，可会笑办理档案迁移，迁移至用人单位或用人单位所在地的人才中心。

  + 五险包括养老保险、医疗保险、失业保险、工伤保险和生育保险，是法定必须缴纳的；一金指住房公积金。

  + 养老保险、医疗保险和失业保险，由用人单位和个人共同缴纳的保费；工伤保险和生育保险完全是由用人单位承担的，个人不需要缴纳。

  + 试用期也是合同期的组成部分，不应排除在外。用人单位给员工上保险（也就是五险一金中的五险）是法定义务，不取决于当事人是否在试用期；不取决于当事人自愿与否，即使员工表示不需要交保险也不行，而且商业保险不能替代社会保险。

  参考：
  + [[http://www.hnrlzysc.com/mingyan/2277.html][毕业生关于三方、户口、档案、五险一金问题_湖南人力资源网]]
* 购房资格
  很多地方不是你有钱就可以买房的，还受到如户口、社保等因数的影响，如果想要在工作的城市买房，
  应该早点关注相关的政策。

  + [[https://zhishi.fang.com/xiangou/zige.html][购房资格查询_买房资格测试-房天下知识]]

* 报道证
  「报到证」是应届普通高等学校(普通全日制，也就是统招生)毕业生到就业单位报到的凭证，也是毕业生参加工作时间的初始记载和凭证。

  通常就需要毕业生到报道证上写的地方报道，部分地方也可以网上报道。

